import { IconType } from "react-icons";
import {
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaVuejs,
  FaNodeJs,
  FaGitAlt,
  FaDocker,
  FaAws,
  FaSass,
  FaGulp,
  FaLinux,
  FaBootstrap,
  FaFigma,
  FaLayerGroup,
  FaPlay,
  FaCogs,
  FaMagic,
  FaTools,
  FaPaintBrush,
  FaChartLine,
  FaMobileAlt,
  FaRocket,
  FaCode,
  FaSearch,
} from "react-icons/fa";
import {
  SiJquery,
  SiNextdotjs,
  SiTailwindcss,
  SiWebpack,
  SiAdobephotoshop,
  SiAdobexd,
  SiTypescript,
  SiFirebase,
  SiMui,
  SiReact,
  SiJavascript,
  SiSass,
  SiGithub,
  SiVuedotjs,
  SiMaterialdesignicons,
  SiAmazon,
  SiGulp,
  SiFigma,
} from "react-icons/si";

export const globalIconMap: Record<string, IconType> = {
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaVuejs,
  FaNodeJs,
  FaGitAlt,
  FaDocker,
  FaAws,
  FaSass,
  FaGulp,
  FaLinux,
  FaBootstrap,
  FaFigma,
  FaLayerGroup,
  FaPlay,
  FaCogs,
  FaMagic,
  FaTools,
  FaPaintBrush,
  FaChartLine,
  FaMobileAlt,
  FaRocket,
  FaCode,
  FaSearch,
  SiJquery,
  SiNextdotjs,
  SiTailwindcss,
  SiWebpack,
  SiAdobephotoshop,
  SiAdobexd,
  SiTypescript,
  SiFirebase,
  SiMui,
  SiReact,
  SiJavascript,
  SiSass,
  SiGithub,
  SiVuedotjs,
  SiMaterialdesignicons,
  SiAmazon,
  SiGulp,
  SiFigma,
};

export const globalBrandColors: Record<string, string> = {
  FaHtml5: "#E44D26",
  FaCss3Alt: "#1572B6",
  FaJs: "#F7DF1E",
  FaReact: "#61DAFB",
  FaVuejs: "#42B883",
  FaNodeJs: "#339933",
  FaGitAlt: "#F05032",
  FaDocker: "#2496ED",
  FaAws: "#FF9900",
  FaSass: "#CC6699",
  FaGulp: "#CF4647",
  FaLinux: "#FCC624",
  FaBootstrap: "#7952B3",
  FaFigma: "#F24E1E",
  FaPlay: "#4CAF50",
  FaCogs: "#607D8B",
  FaMagic: "#8B5CF6", // arbitrary defaults for new ones
  FaTools: "#64748B",
  FaPaintBrush: "#F43F5E",
  FaChartLine: "#10B981",
  FaMobileAlt: "#3B82F6",
  FaRocket: "#F97316",
  FaCode: "#06B6D4",
  FaSearch: "#8B5CF6",
  SiJquery: "#0769AD",
  SiNextdotjs: "#000000",
  SiTailwindcss: "#06B6D4",
  SiWebpack: "#8DD6F9",
  SiAdobephotoshop: "#31A8FF",
  SiAdobexd: "#FF61F6",
  SiTypescript: "#3178C6",
  SiFirebase: "#FFCA28",
  SiMui: "#0081CB",
  SiReact: "#61DAFB",
  SiJavascript: "#F7DF1E",
  SiSass: "#CC6699",
  SiGithub: "#181717",
  SiVuedotjs: "#42B883",
  SiMaterialdesignicons: "#1976D2",
  SiAmazon: "#FF9900",
  SiGulp: "#CF4647",
  SiFigma: "#F24E1E",
};

/**
 * Returns a React Icon component given an icon string from JSON data.
 * Falls back to FaCogs if the icon doesn't exist in the map.
 */
export function getIcon(iconName: string): IconType {
  return globalIconMap[iconName] || FaCogs;
}

/**
 * Returns a brand color for a given icon string.
 * Falls back to the primary brand color reference or plain blue if missing.
 */
export function getBrandColor(iconName: string, fallback: string = "var(--color-primary-500)"): string {
  return globalBrandColors[iconName] || fallback;
}
